### ISSUE TITLE
Implement updater

### ISSUE THREAD

**Issue by neilpie** [pie/load-uploads-from-production#1]

**Comment by brad1066** [comment]
Hey @neilpie, I am going to need access to add some secrets to the repo to get the script working

**Comment by neilpie** [comment]
Did this get sorted @Bradley Hastings ***@***.***> ?
Kind Regards,
Neil

----------------
Neil Pie
Director & Lead Developer

PIE - High Quality WordPress Development
Tel:  +44 (0)20 7873 2224

Need help with something urgent? Email our support desk our
***@***.***

**Comment by brad1066** [comment]
Yeah, I have settings access now @neilpie. I'll add in the secrets required. I will need a reminder how the Automatic version incrementation works for this, as I have set the script to deploy the files to our server at the end of the job which updates the plugin version

**Comment by brad1066** [comment]
The secrets have been added now @neilpie. When you get five, can you review the pull request associated with the branch I made for this please, and then run a test update to a patch version please
