### ISSUE TITLE
Implement Cache Management

### ISSUE THREAD

**Issue by neilpie** [pie/load-uploads-from-production#2]
Initally just a 'clear cache' tool in the UI, but potentially it would be nice to be able to review all cached items and purge them individually if required.

Clear cache for 1.1, then punt cache management to future release

**Comment by brad1066** [comment]
@neilpie, this is ready to review. I have made a pull request. Currently the code is only capable of clearing the cache from the database using an ajax action on a button click on the Settings > General page. A 'Manage Production Images Cache' Page might be more appropriate, with a title with the button to clear, and a frame below that allowing the images to be viewed that are cached (with the urls next to/below them probably)
